print(True and True)
print(True and False)
print(False and True)
print(False and True)
print('-'*50)
print(8>7 and 6>5)
print(8>7 and 6<5)
print(8<7 and 10/0)
print('-'*50)
print(False or False)
print(True or False)
print(False or True)
print(True or True)
print('-'*50)
print(not True)
print(not False)
print(not(8>7))